import { css } from "styled-components"
import { Box, SeasonThreePoints, Text } from "../../../blocks"

type ReferralBenefitProps = {
  text: string;
}

const ReferralBenefit = ({ text }: ReferralBenefitProps) => {
  return (
    <Box
      display="flex"
      alignItems="center"
      gap="spacing-xs"
      width="100%"
    >
      <SeasonThreePoints width={21} height={21} />
      <Text
        variant="bs-regular"
        css={css`
          color: rgba(255, 255, 255, 0.75);
          flex: 1;
        `}
      >
        {text}
      </Text>
    </Box>
  );
};


export const ReferralProgram = () => {
  const benefits = [
    {
      text: "You earn 16% Points generated by your invites"
    },
    {
      text: "You earn 8% Points generated by the people they invite"
    },
    {
      text: "Unlock invites by ensuring your invites progress to Lv. 10"
    }
  ];

  return (
    <Box
      display="flex"
      flexDirection="column"
      gap="spacing-xs"
      padding="spacing-md"
      borderRadius="radius-md"
      width="100%"
      position="relative"
      css={css`
        background: radial-gradient(109.87% 94.08% at 50% 5.92%, #131220 75.21%, #291D39 100%);
        box-sizing: border-box;
        overflow: hidden;

        &::before {
          content: '';
          position: absolute;
          inset: 0;
          border-radius: inherit;
          padding: 1px;
          background: rgba(255, 255, 255, 0.10);
          -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
          mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);
          -webkit-mask-composite: xor;
          mask-composite: exclude;
        }
      `}
    >
      <Text
        variant="h3-semibold"
        css={css`
          text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
          background: linear-gradient(180deg, rgba(255, 255, 255, 1) 50%, rgba(201, 104, 231, 1) 100%);
          -webkit-background-clip: text;
          background-clip: text;
          -webkit-text-fill-color: transparent;
        `}
      >
        S3 Referral Program
      </Text>

      <Box
        display="flex"
        flexDirection="column"
        gap="spacing-sm"
      >
        {benefits.map((benefit, index) => (
          <ReferralBenefit
            key={index}
            text={benefit.text}
          />
        ))}
      </Box>
    </Box>
  );
};
