import { css } from "styled-components"
import { Box, Text } from "../../../blocks"

type ReferralBenefitProps = {
  icon: React.ReactNode;
  text: string;
}

const ReferralBenefit = ({ icon, text }: ReferralBenefitProps) => {
  return (
    <Box
      display="flex"
      alignItems="flex-start"
      gap="spacing-xs"
      width="100%"
    >
      <Box
        display="flex"
        alignItems="center"
        justifyContent="center"
        css={css`
          width: 21px;
          height: 21px;
          flex-shrink: 0;
        `}
      >
        {icon}
      </Box>
      <Text 
        variant="bs-regular"
        css={css`
          color: rgba(255, 255, 255, 0.75);
          flex: 1;
        `}
      >
        {text}
      </Text>
    </Box>
  );
};

// Placeholder icon component for the referral benefits
const BenefitIcon = ({ color }: { color: string }) => (
  <Box
    css={css`
      width: 21px;
      height: 21px;
      border-radius: 50%;
      background: ${color};
      display: flex;
      align-items: center;
      justify-content: center;
    `}
  >
    <Text variant="bs-bold" color="text-primary" css={css`font-size: 10px;`}>%</Text>
  </Box>
);

export const ReferralProgram = () => {
  const benefits = [
    {
      icon: <BenefitIcon color="#D548EC" />,
      text: "You earn 16% Points generated by your invites"
    },
    {
      icon: <BenefitIcon color="#F0A000" />,
      text: "You earn 8% Points generated by the people they invite"
    },
    {
      icon: <BenefitIcon color="#00A47F" />,
      text: "Unlock invites by ensuring your invites progress to Lv. 10"
    }
  ];

  return (
    <Box
      display="flex"
      flexDirection="column"
      gap="spacing-xs"
      padding="spacing-md"
      borderRadius="radius-md"
      width="100%"
      css={css`
        border: 1px solid rgba(255, 255, 255, 0.1);
        background: radial-gradient(50% 50% at 73% 50%, rgba(19, 18, 32, 1) 75%, rgba(41, 29, 57, 1) 100%);
        box-sizing: border-box;
      `}
    >
      <Text
        variant="h3-semibold"
        css={css`
          text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
          background: linear-gradient(180deg, rgba(255, 255, 255, 1) 50%, rgba(201, 104, 231, 1) 100%);
          -webkit-background-clip: text;
          background-clip: text;
          -webkit-text-fill-color: transparent;
        `}
      >
        S3 Referral Program
      </Text>

      <Box
        display="flex"
        flexDirection="column"
        gap="spacing-sm"
      >
        {benefits.map((benefit, index) => (
          <ReferralBenefit 
            key={index}
            icon={benefit.icon}
            text={benefit.text}
          />
        ))}
      </Box>
    </Box>
  );
};
